version: 2
updates:
  - package-ecosystem: "npm"
    directories:
      - "/mobile"
      - "/scripts/packages/*"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 5
    groups:
      npm-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
        group-by: "dependency-name"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "09:00"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 2
