#!/bin/sh
set -e

npx flowgen --quiet lib/typescript/types.d.ts -o lib/typescript/types.js.flow
npx flowgen --quiet lib/typescript/logger.d.ts -o lib/typescript/logger.js.flow
npx flowgen --quiet lib/typescript/to-logger-metadata.d.ts -o lib/typescript/to-logger-metadata.js.flow

cat > lib/typescript/throw-logged-error.js.flow <<'EOF'
/**
 * Flowtype definitions for throw-logged-error
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.21.0
 */

import type {LoggerManager} from './types';

declare export var throwLoggedError: (
  logger: LoggerManager
) => (error: Error | string) => empty;
EOF

cat > lib/typescript/index.js.flow <<'EOF'
/**
 * Flowtype definitions for index
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.21.0
 */

import {LoggerLevel as LoggerLevelValue} from './types';
import {getLogger as getLoggerValue, noOpLogger as noOpLoggerValue, setLogger as setLoggerValue} from './logger';
import {throwLoggedError as throwLoggedErrorValue} from './throw-logged-error';
import {toLoggerMetadata as toLoggerMetadataValue} from './to-logger-metadata';
import type {
  LoggerEntry as LoggerEntryType,
  LoggerLevelType,
  LoggerManager as LoggerManagerType,
  LoggerMessage as LoggerMessageType,
  LoggerMetadata as LoggerMetadataType,
  LoggerTransporter as LoggerTransporterType,
  LoggerTransporterOptions as LoggerTransporterOptionsType,
} from './types';

declare export var LoggerLevel: typeof LoggerLevelValue;
declare export type LoggerLevel = LoggerLevelType;
declare export type LoggerEntry = LoggerEntryType;
declare export type LoggerManager = LoggerManagerType;
declare export type LoggerMessage = LoggerMessageType;
declare export type LoggerMetadata = LoggerMetadataType;
declare export type LoggerTransporter = LoggerTransporterType;
declare export type LoggerTransporterOptions = LoggerTransporterOptionsType;
declare export var getLogger: typeof getLoggerValue;
declare export var noOpLogger: typeof noOpLoggerValue;
declare export var setLogger: typeof setLoggerValue;
declare export var throwLoggedError: typeof throwLoggedErrorValue;
declare export var toLoggerMetadata: typeof toLoggerMetadataValue;
declare export var Logger: {
  Level: typeof LoggerLevelValue,
  ...
};
EOF
