name: cardano-wallet-checks

on:
  push:
    branches: [main, develop]
    paths:
      - ".github/workflows/cardano-wallet-checks.yml"
      - "mobile/babel.config.js"
      - "mobile/jest.config.js"
      - "mobile/package-lock.json"
      - "mobile/package.json"
      - "mobile/packages/cardano-wallet/**"
      - "scripts/packages/cardano-wallet/**"
  pull_request:
    branches: [main, develop]
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - ".github/workflows/cardano-wallet-checks.yml"
      - "mobile/babel.config.js"
      - "mobile/jest.config.js"
      - "mobile/package-lock.json"
      - "mobile/package.json"
      - "mobile/packages/cardano-wallet/**"
      - "scripts/packages/cardano-wallet/**"

permissions:
  contents: read

jobs:
  cardano-wallet:
    if: github.event_name != 'pull_request' || github.event.pull_request.draft != true
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - uses: ./.github/actions/mobile-package-check
        with:
          package-name: cardano-wallet
          package-directory: scripts/packages/cardano-wallet
          cache-dependency-path: |
            mobile/package-lock.json
            scripts/packages/cardano-wallet/package-lock.json
          install-mobile: "true"
          mobile-test-path: packages/cardano-wallet
