name: dependency-review

on:
  pull_request:
    branches: [main, develop]
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - "package.json"
      - "package-lock.json"
      - "mobile/package.json"
      - "mobile/package-lock.json"
      - "scripts/packages/**/package.json"
      - "scripts/packages/**/package-lock.json"
      - ".github/workflows/*.yml"
      - ".github/workflows/*.yaml"

permissions:
  contents: read
  pull-requests: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7.0.0

      - name: Dependency review
        uses: actions/dependency-review-action@v5.0.0
        with:
          fail-on-severity: moderate
