name: Create preview build for devices with EAS
on:
  pull_request:
    types: [closed]
    branches:
      - preview
      - preview-next

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: read

jobs:
  preview-build:
    if: github.event.pull_request.merged == true
    runs-on: macos-latest
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: 🏗 Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: "22.12.0"
          cache: npm
          cache-dependency-path: mobile/package-lock.json

      - name: 🏗 Setup EAS
        uses: expo/expo-github-action@c7b66a9c327a43a8fa7c0158e7f30d6040d2481e # v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
          packager: npm

      - name: 📦 Install Dependencies
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: mobile
        run: npm ci

      - name: 🚀 Create preview build
        working-directory: mobile
        run: eas build --profile preview --platform all --no-wait --non-interactive
