name: Create production build for Google Play and Testflight with EAS
on:
  pull_request:
    types: [closed]
    branches:
      - production

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  EAS_BUILD_PROFILE: production
  EXPO_PUBLIC_BUILD_VARIANT: PROD

permissions:
  contents: read

jobs:
  production-build:
    if: github.event.pull_request.merged == true
    runs-on: macos-latest
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: 🏗 Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: "22.12.0"
          cache: npm
          cache-dependency-path: mobile/package-lock.json

      - name: 🏗 Setup EAS
        uses: expo/expo-github-action@c7b66a9c327a43a8fa7c0158e7f30d6040d2481e # v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
          packager: npm

      - name: 📦 Install Dependencies
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: mobile
        run: npm ci

      - name: 🚀 Create production build
        working-directory: mobile
        env:
          EAS_BUILD_PROFILE: production
          EXPO_PUBLIC_BUILD_VARIANT: PROD
        run: eas build --profile production --platform all --non-interactive

      - name: 🚀 Submit build to Apple TestFlight
        working-directory: mobile
        env:
          EAS_BUILD_PROFILE: production
          EXPO_PUBLIC_BUILD_VARIANT: PROD
        run: eas submit --platform ios --profile production --non-interactive --latest

      - name: 🚀 Submit build to Android Google Play
        working-directory: mobile
        env:
          EAS_BUILD_PROFILE: production
          EXPO_PUBLIC_BUILD_VARIANT: PROD
        run: eas submit --platform android --profile production --non-interactive --latest
